import { chromium } from 'playwright';
const dir='/private/tmp/claude-501/-Users-ivanballesteros-Balles-Hosteleros/31dd154f-6f00-433f-8baa-5f75a65af974/scratchpad';
const b=await chromium.launch();
const p=await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:4321/experiencia',{waitUntil:'networkidle',timeout:90000});
await p.waitForTimeout(2000);
const gal=p.locator('section:has(img[alt="Música en vivo durante la cena"])').first();
await gal.scrollIntoViewIfNeeded(); await p.waitForTimeout(1200);
await gal.screenshot({path:`${dir}/06-galeria.png`});
const pie=p.locator('#contacto').first();
await pie.scrollIntoViewIfNeeded(); await p.waitForTimeout(800);
await pie.screenshot({path:`${dir}/07-pie.png`});
await b.close(); console.log('ok');
